# Generated by Django 5.2.10 on 2026-01-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('espera', 'En Espera'), ('atendido', 'Atendido')], default='programado', max_length=20),
        ),
    ]
