# Generated by Django 5.2.10 on 2026-01-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='informacion_medica',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
