# Generated by Django 5.2.10 on 2026-01-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paciente_informacion_medica'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='visitas/'),
        ),
    ]
