# Generated by Django 5.2.10 on 2026-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_visita_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='visitas/'),
        ),
    ]
