# Generated by Django 5.2.10 on 2026-01-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ausencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
